Repository grow-playground/type-time, pull requests merged in 2023-12, with the labels that each got.

#21 문제 페이지 작업하기
  app/api/quiz-submission/route.ts
  app/quizzes/[id]/choice-form.tsx
  app/quizzes/[id]/page.tsx
  app/quizzes/[id]/quiz.tsx
  components/common/loading-spinner/loading-spinner.tsx
  hooks/quiz.ts
  libs/database.types.ts
  package-lock.json
  package.json
  tailwind.config.js
  utils/supabase/client.ts
  utils/supabase/server.ts
Labels: 기능

#18 정답 조회 페이지 작업하기
  app/(main)/page.tsx
  app/globals.css
  app/not-found.tsx
  app/quizzes/[id]/answer/page.tsx
  assets/images/type-time.png
  assets/images/user-profile.png
  components/common/buttons/back-button.tsx
  components/common/buttons/button.tsx
  components/header.tsx
  package-lock.json
Labels: 기능

#23 모달 컴포넌트 작업
  app/api/quiz-submission/route.ts
  app/layout.tsx
  app/quizzes/[id]/quiz.tsx
  components/common/modals/dimmer.tsx
  components/common/modals/modal.tsx
  components/common/modals/use-temp-modal.tsx
  package-lock.json
  package.json
  providers/overlay-provider.tsx
  providers/query-provider.tsx
Labels: 기능

#25 컴포넌트 라이브러리 설치
  .eslintrc.json
  app/globals.css
  app/quizzes/[id]/quiz.tsx
  components.json
  components/common/buttons/button.tsx
  components/ui/accordion.tsx
  libs/utils.ts
  package-lock.json
  package.json
  tailwind.config.js
Labels: 스타일

#29 queryOptions 리팩토링
  app/quizzes/[id]/choice-form.tsx
  app/quizzes/[id]/page.tsx
  app/quizzes/[id]/quiz.tsx
  hooks/quiz.ts
  services/quiz/api.ts
  services/quiz/hooks.ts
  services/quiz/options.ts
Labels: 리팩토링

#27 탭 컴포넌트 작업
  app/quizzes/[id]/layout.tsx
  app/quizzes/[id]/loading.tsx
  app/quizzes/[id]/page.tsx
  app/quizzes/[id]/questions/page.tsx
  components/common/link/nav-link.tsx
  components/common/loading-spinner/loading-spinner.tsx
Labels: 기능

#35 마크다운 컴포넌트 분리 및 UI 정리
  app/globals.css
  app/quizzes/[id]/choice-form.tsx
  app/quizzes/[id]/page.tsx
  components/ui/markdown.tsx
Labels: 기능, 스타일

#34 헤더 컴포넌트 작업
  app/(main)/page.tsx
  app/auth/kakao-button.tsx
  app/auth/page.tsx
  app/globals.css
  app/layout.tsx
  app/not-found.tsx
  app/quizzes/[id]/answer/page.tsx
  app/quizzes/[id]/choice-form.tsx
  app/quizzes/[id]/layout.tsx
  app/quizzes/[id]/loading.tsx
  assets/images/back-icon.png
  assets/images/user-profile.png
  components/common/buttons/back-button.tsx
  components/common/buttons/button.tsx
  components/common/headers/back-header.tsx
  components/common/headers/base-header.tsx
  components/common/headers/header.tsx
  components/common/headers/profile.tsx
  components/common/link/nav-link.tsx
  package-lock.json
  tailwind.config.js
Labels: 스타일, 리팩토링

#20 유저 페이지 작업하기
  .husky/pre-commit
  app/my/page.tsx
  services/quiz/api.ts
  services/quiz/hooks.ts
  services/quiz/options.ts
Labels: 기능

#36 퀴즈 페이지에서 힌트 기능 추가
  app/quizzes/[id]/choice-form.tsx
  app/quizzes/[id]/layout.tsx
  app/quizzes/[id]/page.tsx
  components/ui/badge.tsx
  components/ui/markdown.tsx
  libs/database.types.ts
  services/quiz/api.ts
  services/quiz/options.ts
Labels: 기능

#38 메인 페이지 퀴즈 컴포넌트 작업
  .husky/pre-push
  app/(main)/page.tsx
  app/(main)/quiz-table.tsx
  app/api/quiz-submission/route.ts
  components/common/buttons/button.tsx
  components/quiz/table/columns.tsx
  components/quiz/table/data-table.tsx
  components/ui/checkbox.tsx
  components/ui/dropdown-menu.tsx
  components/ui/markdown.tsx
  components/ui/table.tsx
  libs/models.ts
  package-lock.json
  package.json
  services/quiz/api.ts
  services/quiz/hooks.ts
  services/quiz/options.ts
Labels: 기능

#44 댓글 기능 구현
  app/(main)/page.tsx
  app/(main)/quiz-table.tsx
  app/quizzes/[id]/(trying)/choice-form.tsx
  app/quizzes/[id]/(trying)/layout.tsx
  app/quizzes/[id]/(trying)/loading.tsx
  app/quizzes/[id]/(trying)/page.tsx
  app/quizzes/[id]/(trying)/questions/page.tsx
  app/quizzes/[id]/answer/page.tsx
  app/quizzes/[id]/answers/_components/comments.tsx
  app/quizzes/[id]/answers/_components/quiz-answer.tsx
  app/quizzes/[id]/answers/error.tsx
  app/quizzes/[id]/answers/layout.tsx
  app/quizzes/[id]/answers/loading.tsx
  app/quizzes/[id]/answers/page.tsx
  app/quizzes/[id]/quiz.tsx
  components/common/buttons/back-button.tsx
  components/common/headers/back-header.tsx
  components/common/headers/profile.tsx
  components/quiz/table/columns.tsx
  components/ui/avatar.tsx
  components/ui/separator.tsx
  components/ui/skeleton.tsx
  components/ui/textarea.tsx
  libs/database.types.ts
  libs/models.ts
  package-lock.json
  package.json
  services/comment/api.ts
  services/comment/hooks.ts
  services/comment/options.ts
  services/quiz/api.ts
  services/quiz/hooks.ts
  services/quiz/options.ts
Labels: 기능, 스타일

#46 사이드바 컴포넌트 작업
  .husky/pre-push
  app/(main)/page.tsx
  app/layout.tsx
  assets/svgs/hamburger-icon.svg
  assets/svgs/logout-icon.svg
  assets/svgs/profile-icon.svg
  components/common/headers/back-header.tsx
  components/common/headers/base-header.tsx
  components/common/headers/menu.tsx
  components/common/headers/profile.tsx
  components/ui/sheet.tsx
  package-lock.json
  package.json
Labels: 스타일

#51 퀴즈 데이터 없으면 NotFound 렌더링
  app/not-found.tsx
  app/quizzes/[id]/(trying)/page.tsx
  app/quizzes/[id]/_components/choice-form.tsx
  app/quizzes/[id]/layout.tsx
  app/quizzes/[id]/loading.tsx
  app/quizzes/[id]/page.tsx
  app/quizzes/[id]/questions/page.tsx
  components/common/not-found/not-found.tsx
Labels: 스타일

#47 퀴즈 출제 기능
  app/quizzes/writer/_components/writer-form.tsx
  services/quiz/api.ts
  services/quiz/hooks.ts
Labels: 기능

#43 문제 출제 UI 및 폼 데이터 관리
  app/quizzes/[id]/_components/choice-form.tsx
  app/quizzes/[id]/answers/_components/quiz-answer.tsx
  app/quizzes/[id]/page.tsx
  app/quizzes/writer/_components/choices.tsx
  app/quizzes/writer/_components/hints.tsx
  app/quizzes/writer/_components/title-and-difficulty.tsx
  app/quizzes/writer/_components/writer-form-schema.ts
  app/quizzes/writer/_components/writer-form.tsx
  app/quizzes/writer/layout.tsx
  app/quizzes/writer/page.tsx
  components/common/markdown/markdown-editor.tsx
  components/common/markdown/markdown.tsx
  components/ui/button.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/select.tsx
  package-lock.json
  package.json
  services/quiz/api.ts
  services/quiz/hooks.ts
Labels: 기능

#50 Seo 관련 작업
  .env.local.example
  app/api/quizzes/[id]/route.ts
  app/api/quizzes/route.ts
  app/google-analytics.tsx
  app/layout.tsx
  app/opengraph-image.png
  app/quizzes/[id]/answers/layout.tsx
  app/quizzes/sitemap.ts
  app/quizzes/writer/_components/hints.tsx
  app/robots.ts
  app/sitemap.ts
  gtag.js
Labels: 기능

#52 유저 페이지 스타일 작업
  app/my/page.tsx
  app/quizzes/[id]/page.tsx
  app/user/[id]/_components/quiz-table.tsx
  app/user/[id]/_components/user-info.tsx
  app/user/[id]/layout.tsx
  app/user/[id]/not-found.tsx
  app/user/[id]/page.tsx
  components/common/headers/menu.tsx
  components/common/headers/profile.tsx
  services/quiz/api.ts
  services/user/api.ts
  services/user/hook.ts
  services/user/options.ts
Labels: 스타일

#57 스토리북 및 크로마틱 작업
  .eslintrc.json
  .github/workflows/chromatic.yml
  .github/workflows/deploy.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  app/Button.stories.tsx
  package-lock.json
  package.json
Labels: 기능

#56 테이블 디자인 작업
  app/(main)/page.tsx
  app/(main)/quiz-table.tsx
  app/globals.css
  assets/images/check-icon.png
  assets/images/search-icon.png
  assets/images/x-icon.png
  components/common/markdown/markdown.tsx
  components/quiz/table/columns.tsx
  components/quiz/table/data-table.tsx
Labels: 스타일

#54 퀴즈 솔루션 탭
  app/quizzes/[id]/_components/choice-form.tsx
  app/quizzes/[id]/answers/layout.tsx
  app/quizzes/[id]/answers/loading.tsx
  app/quizzes/[id]/answers/page.tsx
  app/quizzes/[id]/layout.tsx
  app/quizzes/[id]/page.tsx
  app/quizzes/[id]/questions/loading.tsx
  app/quizzes/[id]/questions/page.tsx
  services/quiz-submission/api.ts
  services/quiz-submission/hook.ts
  services/quiz-submission/options.ts
  services/quiz/api.ts
  services/quiz/hooks.ts
  services/quiz/options.ts
Labels: 기능, 리팩토링
